import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {randomUUID,generateKeyPairSync,sign} from 'node:crypto';
import sharp from 'sharp';
import {unlink} from 'node:fs/promises';
import path from 'node:path';
import {uploadMedia,readMedia,deleteMedia} from '../../src/server/media';
import {verifyAppleToken} from '../../src/lib/appleAuth';
import {NextRequest} from 'next/server';
import {authenticate} from '../../src/server/accounts';
import {seal,SESSION_COOKIE} from '../../src/lib/auth';
import {database,transaction} from '../../src/server/db';
import {createListing,getListing,listListings,updateListing,openConversation,sendMessage,listMessages,updateConversation,setBlock} from '../../src/server/marketplace';
import {createOffer,resolveOffer} from '../../src/server/offers';
import {createSession,refreshSession} from '../../src/server/accounts';
import {eligibility,shouldDeliver,processNextNotification} from '../../src/server/notificationWorker';
import {updateProfile,publicProfile,rateUser,report,adminReports,moderate} from '../../src/server/community';
import {DeliveryError} from '../../src/server/notificationTransport';
import {deleteAccount,revokeSession} from '../../src/server/accountDeletion';
import {MODELS} from '../../src/data/catalog';
import {chipsForModel,yearsForChip,optionsForYear} from '../../src/data/modelYears';

async function main() {
  assert.equal(new URL(process.env.DATABASE_URL!).pathname,'/usedfruit_staging','Tests only run against the isolated staging database');
  const db=database(),ids=[randomUUID(),randomUUID(),randomUUID()],run=randomUUID();
  const [seller,buyer,stranger]=ids;
  for(const id of ids)await db.query("INSERT INTO users(id,name,email,email_verified,email_notifications,onboarding_completed) VALUES($1,$2,$3,true,true,true)",[id,'Backend Test '+run.slice(0,8),id+'@example.invalid']);
  let passed=0;const mediaIds:string[]=[];
  const check=(name:string)=>{passed++;console.log('PASS '+name);};
  try {
    const pair=generateKeyPairSync('rsa',{modulusLength:2048});
    const jwk={...pair.publicKey.export({format:'jwk'}),kid:'synthetic-test-key',alg:'RS256',use:'sig'};
    const claims={iss:'https://appleid.apple.com',aud:'de.usedfruit.app',sub:'synthetic-apple-sub',nonce:'test-nonce',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+300,email:'test@privaterelay.appleid.com',email_verified:'true'};
    const token=(patch:Record<string,unknown>={})=>{const h=Buffer.from(JSON.stringify({alg:'RS256',kid:jwk.kid})).toString('base64url'),p=Buffer.from(JSON.stringify({...claims,...patch})).toString('base64url'),v=h+'.'+p;return v+'.'+sign('RSA-SHA256',Buffer.from(v),pair.privateKey).toString('base64url');};
    assert.equal(verifyAppleToken(token(),[jwk],claims.aud,claims.nonce).email,claims.email);
    for(const patch of [{iss:'https://attacker.invalid'},{aud:'wrong-app'},{nonce:'wrong-nonce'},{exp:1},{iat:Math.floor(Date.now()/1000)+3600}])assert.throws(()=>verifyAppleToken(token(patch),[jwk],claims.aud,claims.nonce));
    assert.throws(()=>verifyAppleToken(token().replace(/.$/,'!'),[jwk],claims.aud,claims.nonce));
    check('Apple signature, issuer, audience, nonce, expiry and verified relay email');
    const native=await transaction(c=>createSession(c,buyer,'ios'));
    assert.equal((await authenticate(new NextRequest('https://staging.usedfruit.de/api/v1/me',{headers:{Authorization:'Bearer '+native.accessToken}})))?.id,buyer);
    const web=await transaction(c=>createSession(c,buyer,'web'));
    const cookie=SESSION_COOKIE+'='+seal({kind:'session',sid:web.id,sub:buyer,name:'Ignored display name',exp:Math.floor(Date.now()/1000)+300});
    await assert.rejects(()=>authenticate(new NextRequest('https://staging.usedfruit.de/api/v1/me',{method:'PATCH',headers:{cookie,origin:'https://attacker.invalid'}})),{code:'invalid_origin'});
    assert.equal((await authenticate(new NextRequest('https://staging.usedfruit.de/api/v1/me',{headers:{cookie}})))?.id,buyer);
    await db.query("UPDATE sessions SET expires_at=now()-interval '1 second' WHERE id=$1",[native.id]);
    await assert.rejects(()=>authenticate(new NextRequest('https://staging.usedfruit.de/api/v1/listings',{headers:{Authorization:'Bearer '+native.accessToken}}),false),{code:'unauthorized'});
    check('Web and native sessions resolve the same ID; CSRF and expired bearer tokens rejected');
    const original=await sharp({create:{width:8,height:8,channels:3,background:'#00ff00'}}).jpeg().withMetadata().toBuffer();
    const uploaded=await uploadMedia(seller,new Request('https://staging.usedfruit.de/api/v1/media',{method:'POST',headers:{'content-type':'image/jpeg'},body:new Uint8Array(original)}));mediaIds.push(uploaded.id);
    const image=await readMedia(uploaded.id,seller),metadata=await sharp(Buffer.from(await image.arrayBuffer())).metadata();
    assert.equal(metadata.format,'webp');assert.equal(metadata.exif,undefined);
    await assert.rejects(()=>readMedia(uploaded.id,buyer),{code:'not_found'});
    await updateProfile(seller,{coverMediaId:uploaded.id});assert.equal((await readMedia(uploaded.id,null)).status,200);
    await assert.rejects(()=>uploadMedia(seller,new Request('https://staging.usedfruit.de/api/v1/media',{method:'POST',headers:{'content-type':'image/jpeg'},body:'not an image'})),{code:'invalid_image'});
    await deleteMedia(uploaded.id,seller);await assert.rejects(()=>readMedia(uploaded.id,seller),{code:'not_found'});
    check('image format validation, metadata removal, ownership and deletion');
    const model=MODELS.find(x=>x.categoryId==='iphone'&&!x.disabled)!;
    const chip=chipsForModel(model)[0],year=yearsForChip(model,chip)[0],options=optionsForYear(model,year);
    const input={categoryId:model.categoryId,modelId:model.id,priceCents:50000,city:'Heilbronn',postalCode:'74072',specs:{chip,year,colorId:options.colors[0].id,size:options.sizes?.[0],memory:options.memory?.[0],storage:options.storage?.[0],condition:'sehr-gut',originalBox:true,shippingScope:'local',simLock:'unlocked',batteryMaxCapacityPercent:92,serialNumber:'PRIVATE-TEST-SERIAL'}};
    const key=randomUUID();
    const [listing,repeated]=await Promise.all([createListing(seller,input,key),createListing(seller,input,key)]);
    assert.equal(listing.id,repeated.id);assert.match(listing.number,/^\d{10,}$/);check('concurrent publication is idempotent');
    await assert.rejects(()=>createListing(seller,{...input,priceCents:60000},key),{code:'idempotency_conflict'});
    await assert.rejects(()=>createListing(seller,{...input,specs:{...input.specs,simLock:'unknown'}},randomUUID()),{code:'invalid_input'});check('invalid variants and reused keys rejected');
    const publicListing=await getListing(listing.id,buyer);assert.equal(publicListing.privateSpecs,null);assert.ok(!JSON.stringify(publicListing).includes('PRIVATE-TEST-SERIAL'));
    await assert.rejects(()=>updateListing(listing.id,buyer,{version:1,priceCents:1}),{code:'not_found'});check('private fields and listing ownership protected');
    const cheaper=await createListing(seller,{...input,priceCents:40000},randomUUID());
    const firstPage=await listListings(buyer,new URLSearchParams({sort:'price-asc',limit:'1',minPriceCents:'40000'}));
    assert.equal(firstPage.items[0].id,cheaper.id);assert.ok(firstPage.nextCursor);
    const nextPage=await listListings(buyer,new URLSearchParams({sort:'price-asc',limit:'1',minPriceCents:'40000',cursor:firstPage.nextCursor!}));
    assert.equal(nextPage.items[0].id,listing.id);
    const nearby=await listListings(buyer,new URLSearchParams({lat:'49.14',lng:'9.22',radiusKm:'20',sort:'nearest'}));
    assert.ok(nearby.items.some(x=>x.id===listing.id));
    assert.equal((await listListings(buyer,new URLSearchParams({shipping:'yes'}))).items.some(x=>x.id===listing.id),false);
    check('server search filters, stable pagination, price sorting and local radius');
    const conversation=await openConversation(buyer,listing.id);
    await assert.rejects(()=>listMessages(stranger,conversation.id,null),{code:'not_found'});
    await updateProfile(buyer,{name:'Renamed Buyer'});
    const messageKey=randomUUID();
    const [message,duplicate]=await Promise.all([sendMessage(buyer,conversation.id,{text:'Test message'},messageKey),sendMessage(buyer,conversation.id,{text:'Test message'},messageKey)]);
    assert.equal(message.id,duplicate.id);check('chat authorization and stable identity after rename');
    const jobs=(await db.query('SELECT *,extract(epoch from (due_at-created_at))::int AS delay FROM notification_outbox WHERE message_id=$1',[message.id])).rows;
    assert.equal(jobs.length,2);assert.equal(jobs.find(x=>x.channel==='email').delay,120);check('one durable email job per message, due after 120 seconds');
    const email=jobs.find(x=>x.channel==='email');
    assert.equal(await transaction(async c=>shouldDeliver(await eligibility(c,email.id))),true);
    await updateConversation(seller,conversation.id,{readSequence:message.sequence});
    assert.equal(await transaction(async c=>shouldDeliver(await eligibility(c,email.id))),false);check('read message suppresses email');
    const second=await sendMessage(buyer,conversation.id,{text:'Second test'},randomUUID());
    const secondJob=(await db.query("SELECT id FROM notification_outbox WHERE message_id=$1 AND channel='email'",[second.id])).rows[0];
    assert.notEqual(secondJob.id,email.id);
    await updateConversation(seller,conversation.id,{readSequence:second.sequence});
    assert.equal(await transaction(async c=>shouldDeliver(await eligibility(c,secondJob.id))),false);
    await db.query('DELETE FROM message_reads WHERE message_id=$1 AND user_id=$2',[second.id,seller]);
    assert.equal(await transaction(async c=>shouldDeliver(await eligibility(c,secondJob.id))),true);
    check('position cursor alone does not mark unseen messages read');
    await updateProfile(seller,{emailNotifications:false});
    assert.equal(await transaction(async c=>shouldDeliver(await eligibility(c,secondJob.id))),false);
    await updateProfile(seller,{emailNotifications:true});
    await updateConversation(seller,conversation.id,{muted:true});
    assert.equal(await transaction(async c=>shouldDeliver(await eligibility(c,secondJob.id))),false);
    await updateConversation(seller,conversation.id,{muted:false,active:true});
    const push=(await db.query("SELECT id FROM notification_outbox WHERE message_id=$1 AND channel='push'",[second.id])).rows[0];
    assert.equal(await transaction(async c=>shouldDeliver(await eligibility(c,push.id))),false);check('independent deadlines, email preference, mute and active-chat push suppression');
    await setBlock(seller,buyer,true);
    await assert.rejects(()=>getListing(listing.id,buyer),{code:'not_found'});
    await assert.rejects(()=>publicProfile(buyer,seller),{code:'not_found'});
    await assert.rejects(()=>sendMessage(buyer,conversation.id,{text:'blocked'},randomUUID()),{code:'not_found'});
    assert.equal((await listListings(buyer,new URLSearchParams())).items.some(x=>x.id===listing.id),false);
    assert.equal((await db.query('SELECT state FROM notification_outbox WHERE id=$1',[secondJob.id])).rows[0].state,'cancelled');
    await setBlock(seller,buyer,false);check('reciprocal block applies to search, detail, profile, messaging and pending delivery');
    const complaint=await report(buyer,{listingId:listing.id,reason:'Synthetic moderation check'});
    await assert.rejects(()=>adminReports(buyer),{code:'forbidden'});
    await db.query('INSERT INTO admin_users(user_id) VALUES($1)',[stranger]);
    assert.ok((await adminReports(stranger)).items.some(x=>x.id===complaint.id));
    await moderate(stranger,{action:'ban',userId:seller,reason:'Synthetic ban test'});
    await assert.rejects(()=>getListing(listing.id,buyer),{code:'not_found'});
    await moderate(stranger,{action:'unban',userId:seller,reportId:complaint.id,reason:'Synthetic unban test'});
    assert.equal((await getListing(listing.id,buyer)).sellerId,seller);
    check('reports, explicit admin authorization, ban and unban');
    const otherConversation=await openConversation(stranger,listing.id);
    await assert.rejects(()=>createOffer(buyer,conversation.id,{priceCents:49000},randomUUID()),{code:'price_changed'});
    await assert.rejects(()=>createOffer(seller,conversation.id,{priceCents:50000},randomUUID()),{code:'forbidden'});
    const offerA=await createOffer(buyer,conversation.id,{priceCents:50000},randomUUID()),offerB=await createOffer(stranger,otherConversation.id,{priceCents:50000},randomUUID());
    const outcomes=await Promise.allSettled([resolveOffer(seller,offerA.id,{status:'accepted'}),resolveOffer(seller,offerB.id,{status:'accepted'})]);
    assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);
    assert.equal((await db.query("SELECT count(*)::int AS count FROM offers WHERE listing_id=$1 AND status='accepted'",[listing.id])).rows[0].count,1);check('concurrent acceptance sells a device only once');
    const accepted=(await db.query("SELECT id FROM offers WHERE listing_id=$1 AND status='accepted'",[listing.id])).rows[0];
    await assert.rejects(()=>rateUser(seller,{offerId:accepted.id,score:5}),{code:'rating_unavailable'});
    await db.query("UPDATE offers SET resolved_at=now()-interval '3 days' WHERE id=$1",[accepted.id]);
    await rateUser(seller,{offerId:accepted.id,score:5});
    await assert.rejects(()=>rateUser(seller,{offerId:accepted.id,score:5}),{code:'already_rated'});
    check('two-day rating delay, eligible rating and duplicate prevention');
    const session=await transaction(c=>createSession(c,buyer,'ios'));
    const rotated=await refreshSession(session.refreshToken);
    assert.notEqual(session.refreshToken,rotated.refreshToken);
    await assert.rejects(()=>refreshSession(session.refreshToken),{code:'unauthorized'});
    await assert.rejects(()=>refreshSession(rotated.refreshToken),{code:'unauthorized'});check('refresh token reuse revokes the entire family');
    // Exercise the real claim/transaction path without contacting any delivery provider.
    const deliveries:string[]=[];
    const transport={sendEmail:async(to:string)=>{deliveries.push(to);return 'test-provider-id';},sendPush:async()=>"test-push-id"};
    await updateConversation(seller,conversation.id,{active:false,muted:false});
    const workerMessage=await sendMessage(buyer,conversation.id,{text:'Worker transaction test'},randomUUID());
    const workerJob=(await db.query("SELECT id FROM notification_outbox WHERE message_id=$1 AND channel='email'",[workerMessage.id])).rows[0];
    assert.equal(await processNextNotification(transport,workerJob.id),false);
    await db.query("UPDATE notification_outbox SET due_at=now()-interval '1 second' WHERE id=$1",[workerJob.id]);
    await Promise.all([processNextNotification(transport,workerJob.id),processNextNotification(transport,workerJob.id)]);
    assert.deepEqual(deliveries,[seller+'@example.invalid']);
    assert.equal((await db.query('SELECT state FROM notification_outbox WHERE id=$1',[workerJob.id])).rows[0].state,'sent');
    assert.equal(await processNextNotification(transport,workerJob.id),false);
    check('worker waits until due, claims concurrently once and persists delivery');
    const pushSession=await transaction(c=>createSession(c,seller,'ios'));
    const device=(await db.query("INSERT INTO device_tokens(user_id,session_id,token,environment) VALUES($1,$2,$3,'sandbox') RETURNING id",[seller,pushSession.id,'ab'.repeat(32)])).rows[0];
    const pushJob=(await db.query("SELECT id FROM notification_outbox WHERE message_id=$1 AND channel='push'",[workerMessage.id])).rows[0];
    let pushed=0;
    await updateProfile(seller,{pushNotifications:true});
    await processNextNotification({...transport,sendPush:async()=>{pushed++;return 'test-push';}},pushJob.id);
    assert.equal(pushed,1);assert.equal((await db.query('SELECT count(*)::int AS count FROM notification_deliveries WHERE device_id=$1',[device.id])).rows[0].count,1);
    await revokeSession(pushSession.id);assert.equal((await db.query('SELECT id FROM device_tokens WHERE id=$1',[device.id])).rowCount,0);
    check('push receipts persist and logout removes device without foreign-key failures');
    const failureMessage=await sendMessage(buyer,conversation.id,{text:'Retry boundary test'},randomUUID());
    const failureJob=(await db.query("SELECT id FROM notification_outbox WHERE message_id=$1 AND channel='email'",[failureMessage.id])).rows[0];
    for(let attempt=0;attempt<5;attempt++){
      await db.query("UPDATE notification_outbox SET due_at=now()-interval '1 second' WHERE id=$1",[failureJob.id]);
      await processNextNotification({...transport,sendEmail:async()=>{throw new DeliveryError('synthetic_transient',true);}},failureJob.id);
    }
    assert.equal((await db.query('SELECT state FROM notification_outbox WHERE id=$1',[failureJob.id])).rows[0].state,'failed');
    await db.query("UPDATE notification_outbox SET state='pending',attempts=0,due_at=now() WHERE id=$1",[failureJob.id]);
    await processNextNotification({...transport,sendEmail:async()=>{throw new DeliveryError('synthetic_handoff_unknown',false,true);}},failureJob.id);
    assert.equal((await db.query('SELECT state FROM notification_outbox WHERE id=$1',[failureJob.id])).rows[0].state,'uncertain');
    assert.equal(await processNextNotification(transport,failureJob.id),false);
    check('transient delivery retries stop after five attempts; uncertain handoffs are not resent');
    if(process.env.USED_FRUIT_VERIFY_RESTORE==='1')execFileSync('python3',['scripts/ops/verify-restore.py'],{stdio:'inherit'});
    await deleteAccount(seller);
    assert.equal((await db.query('SELECT name,email,deleted_at FROM users WHERE id=$1',[seller])).rows[0].email,null);
    assert.equal((await db.query('SELECT status FROM listings WHERE id=$1',[listing.id])).rows[0].status,'deleted');check('account deletion removes public content and private account data');
    assert.ok((await listMessages(buyer,conversation.id,null)).items.length>0);
    await assert.rejects(()=>sendMessage(buyer,conversation.id,{text:'Deleted recipient'},randomUUID()),{code:'not_found'});
    check('anonymized history remains readable, deleted accounts cannot receive messages');
    console.log(`${passed} checks passed`);
  } finally {
    // Delete only records belonging to this invocation's three synthetic users.
    await transaction(async c=> {
      await c.query('DELETE FROM moderation_actions WHERE admin_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM reports WHERE reporter_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM admin_users WHERE user_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM notification_deliveries WHERE outbox_id IN (SELECT id FROM notification_outbox WHERE recipient_id=ANY($1::uuid[]))',[ids]);
      await c.query('DELETE FROM notification_outbox WHERE recipient_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM ratings WHERE author_id=ANY($1::uuid[]) OR recipient_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM offers WHERE sender_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM messages WHERE sender_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM conversation_participants WHERE user_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM conversations WHERE buyer_id=ANY($1::uuid[]) OR seller_id=ANY($1::uuid[])',[ids]);
      for(const table of ['favorites','listing_notes','device_tokens','sessions','auth_identities','idempotency_keys','media'])await c.query(`DELETE FROM ${table} WHERE user_id=ANY($1::uuid[])`,[ids]);
      await c.query('DELETE FROM user_blocks WHERE blocker_id=ANY($1::uuid[]) OR blocked_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM listings WHERE seller_id=ANY($1::uuid[])',[ids]);
      await c.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[ids]);
    });
    for(const id of mediaIds)for(const directory of [process.env.USED_FRUIT_MEDIA_DIR!,path.join(path.dirname(process.env.USED_FRUIT_MEDIA_DIR!),'media-trash')])await unlink(path.join(directory,id+'.webp')).catch(()=>{});
    await db.end();
  }
}
main().catch(error=>{console.error(error);process.exitCode=1;});
